// MCP server entry point

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  ListResourcesRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';
import { extractDesignElements } from './extractor/index.js';
import { loadRuleset } from './rules/loader.js';
import { scoreDesign } from './critique/scorer.js';
import { generateDeterministicFixes, applyShadcnReplacements } from './refactor/fixes.js';
import { applyPatches, writePatchedFile } from './refactor/patch-applier.js';
import { generateComponent } from './generate/component-gen.js';
import { generateLayout } from './generate/layout-gen.js';
import { handleError } from './utils/errors.js';
import { logger } from './utils/logger.js';
import { readFileSync } from 'fs';

const server = new Server(
  {
    name: 'design-audit-mcp',
    version: '1.0.0',
  },
  {
    capabilities: {
      tools: {},
      resources: {},
    },
  }
);

// List available tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: 'design_extract',
        description: 'Extract design elements from code (components, layout, spacing, typography, imagery, accessibility)',
        inputSchema: {
          type: 'object',
          properties: {
            code: {
              type: 'string',
              description: 'Source code to extract from',
            },
            filePath: {
              type: 'string',
              description: 'Path to the source file',
            },
          },
          required: ['code', 'filePath'],
        },
      },
      {
        name: 'design_get_ruleset',
        description: 'Get the current design ruleset configuration',
        inputSchema: {
          type: 'object',
          properties: {
            customRulesetPath: {
              type: 'string',
              description: 'Optional path to custom ruleset directory',
            },
          },
        },
      },
      {
        name: 'design_audit',
        description: 'Run a complete design audit: extract, critique, and score design elements',
        inputSchema: {
          type: 'object',
          properties: {
            code: {
              type: 'string',
              description: 'Source code to audit',
            },
            filePath: {
              type: 'string',
              description: 'Path to the source file',
            },
            customRulesetPath: {
              type: 'string',
              description: 'Optional path to custom ruleset directory',
            },
          },
          required: ['code', 'filePath'],
        },
      },
      {
        name: 'design_refactor',
        description: 'Apply deterministic fixes to refactor code based on audit results',
        inputSchema: {
          type: 'object',
          properties: {
            filePath: {
              type: 'string',
              description: 'Path to the file to refactor',
            },
            auditReport: {
              type: 'object',
              description: 'Optional audit report from design_audit',
            },
            applyShadcn: {
              type: 'boolean',
              description: 'Whether to apply shadcn component replacements',
            },
          },
          required: ['filePath'],
        },
      },
      {
        name: 'design_generate',
        description: 'Generate new component or layout code following the design ruleset',
        inputSchema: {
          type: 'object',
          properties: {
            intent: {
              type: 'object',
              description: 'Generation intent (type, description, framework, props)',
            },
            rulesetPath: {
              type: 'string',
              description: 'Optional path to custom ruleset',
            },
          },
          required: ['intent'],
        },
      },
      {
        name: 'design_apply_patch',
        description: 'Apply patches generated by LLM to a file',
        inputSchema: {
          type: 'object',
          properties: {
            filePath: {
              type: 'string',
              description: 'Path to the file to patch',
            },
            patches: {
              type: 'array',
              description: 'Array of patch operations (insert/delete/replace)',
            },
            write: {
              type: 'boolean',
              description: 'Whether to write the patched content to file',
            },
          },
          required: ['filePath', 'patches'],
        },
      },
    ],
  };
});

// Handle tool calls
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    switch (name) {
      case 'design_extract': {
        const { code, filePath } = args as { code: string; filePath: string };
        const extraction = await extractDesignElements(code, filePath);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify(extraction, null, 2),
            },
          ],
        };
      }

      case 'design_get_ruleset': {
        const { customRulesetPath } = args as { customRulesetPath?: string };
        const ruleset = await loadRuleset(customRulesetPath);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify(ruleset, null, 2),
            },
          ],
        };
      }

      case 'design_audit': {
        const { code, filePath, customRulesetPath } = args as {
          code: string;
          filePath: string;
          customRulesetPath?: string;
        };
        const extraction = await extractDesignElements(code, filePath);
        const ruleset = await loadRuleset(customRulesetPath);
        const critique = scoreDesign(extraction, ruleset);
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify(
                {
                  extraction,
                  critique,
                },
                null,
                2
              ),
            },
          ],
        };
      }

      case 'design_refactor': {
        const { filePath, auditReport, applyShadcn } = args as {
          filePath: string;
          auditReport?: unknown;
          applyShadcn?: boolean;
        };
        const code = readFileSync(filePath, 'utf-8');
        const extraction = await extractDesignElements(code, filePath);
        const ruleset = await loadRuleset();
        const critique = auditReport ? (auditReport as { critique: unknown }).critique : scoreDesign(extraction, ruleset);
        
        let patches = generateDeterministicFixes(extraction, critique as { overall: number; spacingRhythm: { score: number }; violations: unknown[] });
        
        if (applyShadcn) {
          const shadcnPatches = applyShadcnReplacements(extraction);
          patches.push(...shadcnPatches);
        }

        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify(
                {
                  patches,
                  summary: `Generated ${patches.length} patches for ${filePath}`,
                },
                null,
                2
              ),
            },
          ],
        };
      }

      case 'design_generate': {
        const { intent, rulesetPath } = args as {
          intent: { type: string; description: string; framework: string; props?: Record<string, unknown> };
          rulesetPath?: string;
        };
        const ruleset = await loadRuleset(rulesetPath);
        const code = generateComponent(intent, ruleset);
        return {
          content: [
            {
              type: 'text',
              text: code,
            },
          ],
        };
      }

      case 'design_apply_patch': {
        const { filePath, patches, write } = args as {
          filePath: string;
          patches: unknown[];
          write?: boolean;
        };
        const patchedContent = applyPatches(filePath, patches as Array<{ type: string; startLine: number; endLine?: number; content: string }>);
        
        if (write) {
          writePatchedFile(filePath, patchedContent);
        }

        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify(
                {
                  success: true,
                  filePath,
                  content: patchedContent,
                },
                null,
                2
              ),
            },
          ],
        };
      }

      default:
        throw new Error(`Unknown tool: ${name}`);
    }
  } catch (error) {
    const errorInfo = handleError(error);
    logger.error('Tool execution failed', { tool: name, error: errorInfo });
    return {
      content: [
        {
          type: 'text',
          text: JSON.stringify({ error: errorInfo.message, code: errorInfo.code }),
        },
      ],
      isError: true,
    };
  }
});

// List resources (empty for now)
server.setRequestHandler(ListResourcesRequestSchema, async () => {
  return {
    resources: [],
  };
});

// Start server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  logger.info('Design Audit MCP server started');
}

main().catch((error) => {
  logger.error('Failed to start server', { error: error instanceof Error ? error.message : 'Unknown error' });
  process.exit(1);
});

